# Generated by Django 3.1.7 on 2021-03-23 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='habilidadesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistencia', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('aceleración', models.IntegerField()),
                ('Agilidad', models.IntegerField()),
                ('flexibilidad', models.IntegerField()),
                ('coordinación', models.IntegerField()),
                ('precisión', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usermodel')),
            ],
        ),
    ]
