# Generated by Django 3.1.7 on 2021-03-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadesuser',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habilidadesuser',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
