# Generated by Django 3.1.7 on 2021-04-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ejercicios', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('duracion', models.IntegerField()),
                ('explicacion', models.CharField(max_length=150)),
                ('link_entreno', models.CharField(max_length=150)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plan', models.IntegerField()),
                ('dias_disponibles', models.IntegerField()),
                ('dias_entrenados', models.IntegerField()),
                ('dias_esta_semana', models.IntegerField()),
                ('num_sesiones', models.IntegerField()),
                ('ultima_semana', models.DateField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rango', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('peso', models.CharField(max_length=3)),
                ('estatura', models.CharField(max_length=3)),
                ('correo', models.EmailField(max_length=254)),
                ('contra', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('puntaje_habilidades', models.IntegerField()),
                ('id_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.rangos')),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.planes')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion_Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ejercicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.ejercicios')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.sesiones')),
            ],
        ),
        migrations.AddField(
            model_name='planes',
            name='id_rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.rangos'),
        ),
        migrations.AddField(
            model_name='planes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.usuarios'),
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_habilidades', models.IntegerField()),
                ('flexibilidad', models.IntegerField()),
                ('fuerza', models.IntegerField()),
                ('resistencia', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('aceleracion', models.IntegerField()),
                ('agilidad', models.IntegerField()),
                ('coordinacion', models.IntegerField()),
                ('precision', models.IntegerField()),
                ('id_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.rangos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='id_rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutsApp.rangos'),
        ),
    ]
