# Generated by Django 3.1.7 on 2021-04-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='id_ejercicios',
        ),
    ]
